<a href="https://colab.research.google.com/github/zubrist/Machine-Learning/blob/main/NaiveBayes_wonMatch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Assigning features and label variables
weather=['Rainy','Rainy','Overcast','Sunny','Sunny','Sunny','Overcast','Rainy','Rainy','Sunny','Rainy']
matchWons=['3','3','3','2','1','1','1','2','1', '2', '2']
humidity=['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal']
winToss=['F','T','F','F','F','T','T','F','F','F','T']

won=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes']

# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
matchWons_encoded=le.fit_transform(matchWons)
humidity_encoded= le.fit_transform(humidity)
winToss_encoded= le.fit_transform(winToss)
target=le.fit_transform(won)

print(weather_encoded)
print(matchWons_encoded)
print(humidity_encoded)
print(winToss_encoded)
print(target)
print("_____________________________________________")

import numpy as np
zipped=zip(weather_encoded,matchWons_encoded,humidity_encoded,winToss_encoded)
features = np.array(list(zipped)).tolist()
print(features)
print("______________________________________________")
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import CategoricalNB

#Create a Gaussian Classifier
model = CategoricalNB()

# Train the model using the training sets
model.fit(features,target)

#Predict Output
#weather : 0 = Overcast; 1 = Rainy ; 2= Sunny
#matchWons : 0 = 1 win ; 1 = 2 wins; 2 = 3 wins
#Humidity : 0 = High  ; 1 = Normal
#WinToss : 0 =False ; 1 = True 
predicted= model.predict([[1, 1, 1 , 1]]) # 1:Rainy, 1:2 wins ; 1:Normal ; 1:True
#print("Predicted Value:", predicted)
if(predicted==0):
  print("Will Win the match ")
else:
  print("Will not win the match")

[1 1 0 2 2 2 0 1 1 2 1]
[2 2 2 1 0 0 0 1 0 1 1]
[0 0 0 0 1 1 1 0 1 1 1]
[0 1 0 0 0 1 1 0 0 0 1]
[0 0 1 1 1 0 1 0 1 1 1]
_____________________________________________
[[1, 2, 0, 0], [1, 2, 0, 1], [0, 2, 0, 0], [2, 1, 0, 0], [2, 0, 1, 0], [2, 0, 1, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 0, 1, 0], [2, 1, 1, 0], [1, 1, 1, 1]]
______________________________________________
Will not win the match
