<a href="https://colab.research.google.com/github/zubrist/Machine-Learning/blob/main/NaiveBayes_carStolen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Assigning features and label variables
color=['Red','Red','Red','Yellow','Yellow','Yellow','Yellow','Yellow','Red','Red']
types=['Sport','Sport','Sport','Sport','Sport','SUV','SUV','SUV','SUV','Sport']
origin=['Domestic','Domestic','Domestic','Domestic','Imported','Imported','Imported','Domestic','Imported','Imported']
stolen=['Yes','No','Yes','No','Yes','No','Yes','No','No','Yes']

# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
color_encoded=le.fit_transform(color)
types_encoded=le.fit_transform(types)
origin_encoded= le.fit_transform(origin)
target=le.fit_transform(stolen)

print(color_encoded)
print(types_encoded)
print(origin_encoded)
print(target)
print("_____________________________________________")

import numpy as np
zipped=zip(color_encoded,types_encoded,origin_encoded)
features = np.array(list(zipped)).tolist()
print(features)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import CategoricalNB

#Create a Gaussian Classifier
model = CategoricalNB()

# Train the model using the training sets
model.fit(features,target)

#Predict Output
#color: 0 = Red; 1 = Yellow
#Types: 0 = SUV ; 1 = Sport
#origin: 0 = Domestic ; 1 = Imported
 
predicted= model.predict([[0, 0, 0 ]])  
#print("Predicted Value:", predicted)
if(predicted==0):
  print("The Car is not stolen")
else:
  print("The Car is Stolen")

[0 0 0 1 1 1 1 1 0 0]
[1 1 1 1 1 0 0 0 0 1]
[0 0 0 0 1 1 1 0 1 1]
[1 0 1 0 1 0 1 0 0 1]
_____________________________________________
[[0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 1, 0], [1, 1, 1], [1, 0, 1], [1, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 1]]
The Car is not stolen
