<a href="https://colab.research.google.com/github/zubrist/Machine-Learning/blob/main/NaiveBayes_playTennis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Assigning features and label variables
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
humidity=['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High']
wind=['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
temp_encoded=le.fit_transform(temp)
humidity_encoded= le.fit_transform(humidity)
wind_encoded= le.fit_transform(wind)
target=le.fit_transform(play)

print(weather_encoded)
print(temp_encoded)
print(humidity_encoded)
print(wind_encoded)
print(target)
print("_____________________________________________")

import numpy as np
zipped=zip(weather_encoded,temp_encoded,humidity_encoded,wind_encoded)
features = np.array(list(zipped)).tolist()
print(features)

#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import CategoricalNB

#Create a Gaussian Classifier
model = CategoricalNB()

# Train the model using the training sets
model.fit(features,target)

#Predict Output
#weather : 0 = Overcast; 1 = Rainy ; 2= Sunny
#Temp : 0 = Cool ; 1 = Hot; 2 = Mild
#Humidity : 0 = High  ; 1 = Normal
#Wind : 0 =Strong  ; 1 = Weak 
predicted= model.predict([[0, 1, 0 , 1]]) # 2:Sunny, 0:Cool ; 0:High ; 0:Strong 
#print("Predicted Value:", predicted)
if(predicted==0):
  print("The Conditions are Not Good to play Tennis Today")
else:
  print("The Condiotions are Okay to play Tennis Today")

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[1 0 1 1 1 0 0 1 1 1 0 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]
_____________________________________________
[[2, 1, 0, 1], [2, 1, 0, 0], [0, 1, 0, 1], [1, 2, 0, 1], [1, 0, 1, 1], [1, 0, 1, 0], [0, 0, 1, 0], [2, 2, 0, 1], [2, 0, 1, 1], [1, 2, 1, 1], [2, 2, 1, 0], [0, 2, 0, 0], [0, 1, 1, 1], [1, 2, 0, 0]]
The Condiotions are Okay to play Tennis Today
